### ISSUE TITLE
Does your patch works for VASP 6.12?

### ISSUE THREAD

**Issue by peter308** [Chengcheng-Xiao/VASP2WAN90_v2_fix#9] opened 2021-09-30 04:10 UTC
Dear Mr. Xiao

May I consult you that does your patch can be applied to VASP 6.12 as well?

My current VASP is version 6.12, and I am also running into projection problems when SOC is included. I would like to know your comments on this regarding using VASP version 6.12.  Can you help? Tks!

with regards,
Peter

**Comment by Chengcheng-Xiao** [comment] 2021-09-30 07:40
Hello there Peter,

No, this patch does not work with VASP v6.1.2 as it only works with v5.4.4. If you have access to version 6.1.2, chances are, you also have access to v6.2.1 in which the SOC bug should've been resolved!

**Comment by shahid-sattar** [comment] 2021-10-04 08:43
Hi Chengcheng,
thanks for the comment. Just want to clarify: wannier3.0 with vasp6.2.1 don't need to incorporate your patch. The issue is already resolved in vasp6.2, right?

**Comment by Chengcheng-Xiao** [comment] 2021-10-04 09:40
Hi @shahid-sattar,

Just to be clear, VASP v6.2.1 did solve the SOC projection loop bug (see [🔗 this link](https://github.com/Chengcheng-Xiao/VASP2WAN90_v2_fix/wiki/what's-wrong-with-the-original-interface%3F#original-symptoms)) but they haven't implemented the `.SPN` file output which my patch provides. 😉

**Comment by shahid-sattar** [comment] 2021-10-04 09:46
Hi, thanks again. 
So we should compile vasp6.2 with your patch as well?

**Comment by Chengcheng-Xiao** [comment] 2021-10-04 10:03
I'm sorry @shahid-sattar but that's a negative. 

My patch **ONLY** works with VASP v5.4.4.

**Comment by peter308** [comment] 2021-10-07 07:49
Dear Mr. Xiao

I am using VASP 6.1.2. I am trying to output the amn files, yet I consistently got this message
"SETROTYLM: ERROR: X and Z are not orthogonal (enough):"
My calculation involved SOC. Do you know does this happens due to the bug that your patch is aiming to solve?
Or is it due to other reasons that are not due to the bug? Appreciate your help!


with regards,
Peter

**Comment by Chengcheng-Xiao** [comment] 2021-10-07 09:33
Hi, @peter308. No, my patch is not aimed at solving your problem. `SETROTYLM` is used to set the spherical harmonics to align with the coordinate system (zaxis:xaxis) of your choosing (for details, see chapter 3, subchapter 3.1 of the official Wannier90 user guide).

Alternatively, since I have limited experience with VASP v6.1.2 so that I'm not sure it doesn't have any bugs,  I would suggest you give VASP v5.4.4+patch or VASP v6.2.1 a try.

**Comment by Chengcheng-Xiao** [comment] 2021-10-10 12:51
Closed due to inactivity.

**Closed as completed by Chengcheng-Xiao** 2021-10-10 12:51 UTC
